version: '3'

services:
  nestapp:
    build: ./nest-example
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./nest-example:/usr/src/app
    environment:
      - NAME=Nest
    networks:
      - nestApp
 
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nestApp
    ports:
      - "80:80"

networks:
  nestApp:
    driver: bridge

